#!/usr/bin/env python3
"""Generate golden HDBSCAN test fixtures from a news-signal JSON file.

Requires:
    pip install hdbscan numpy

Usage:
    python3 internal/hdbscan/testdata/gen_golden.py <path-to-signals.json> [N]

    <path-to-signals.json>  path to the JSON file (array of signal objects
                            with an "embedding" field)
    N                       number of signals to use (default: 100)

Output:
    internal/hdbscan/testdata/golden_mcs<K>_ms<M>.json  for each parameter
    combination listed in PARAM_GRID below.
"""

import argparse
import json
import os
import sys
from collections import Counter

try:
    import hdbscan
    import numpy as np
except ImportError as e:
    sys.exit(f"Missing dependency: {e}\nRun: pip install hdbscan numpy")

# ── Parameter grid ────────────────────────────────────────────────────────────
# Each entry is (min_cluster_size, min_samples).
PARAM_GRID = [
    (2, 1),
    (2, 2),
    (3, 1),
    (3, 3),
    (5, 1),
    (5, 5),
]

CLUSTER_SELECTION_METHOD = "eom"  # excess-of-mass, matches our Go implementation

# ── CLI ───────────────────────────────────────────────────────────────────────

parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("input", help="path to signals JSON file")
parser.add_argument("N", nargs="?", type=int, default=100,
                    help="number of signals to use (default: 100)")
args = parser.parse_args()

# ── Load data ─────────────────────────────────────────────────────────────────

source_path = os.path.abspath(args.input)
N = args.N

print(f"Loading {source_path} …")
with open(source_path) as f:
    data = json.load(f)

if len(data) < N:
    sys.exit(f"Source has only {len(data)} signals; need at least {N}")

subset = data[:N]
embeddings = [s["embedding"] for s in subset]
ids       = [s["id"]        for s in subset]
titles    = [s["title"]     for s in subset]

embs = np.array(embeddings, dtype=np.float32)

# Pre-compute the cosine distance matrix once.
# hdbscan ≥ 0.8.29 dropped 'cosine' from BallTree metrics; pass a precomputed
# distance matrix with metric='precomputed' instead.
print(f"Computing {N}×{N} cosine distance matrix …")
norms = np.linalg.norm(embs, axis=1, keepdims=True)
norms = np.where(norms == 0, 1.0, norms)
embs_n = embs / norms
cos_sim = embs_n @ embs_n.T
cos_sim = np.clip(cos_sim, -1.0, 1.0)
dist_matrix = (1.0 - cos_sim).astype(np.float64)
np.fill_diagonal(dist_matrix, 0.0)

# ── Output directory (same as this script) ────────────────────────────────────

out_dir = os.path.dirname(os.path.abspath(__file__))
source_label = os.path.basename(source_path)

# ── Cluster and write one fixture per parameter combination ───────────────────

for min_cluster_size, min_samples in PARAM_GRID:
    tag = f"mcs{min_cluster_size}_ms{min_samples}"
    print(f"\nRunning HDBSCAN (min_cluster_size={min_cluster_size}, "
          f"min_samples={min_samples}) on {N} signals …")

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric="precomputed",
        cluster_selection_method=CLUSTER_SELECTION_METHOD,
    )
    clusterer.fit(dist_matrix)
    labels = clusterer.labels_.tolist()

    counts = Counter(labels)
    noise_count = counts.pop(-1, 0)
    sizes = sorted(counts.values(), reverse=True)
    print(f"  {len(counts)} clusters, {noise_count} noise")
    if sizes:
        print(f"  Cluster sizes: {sizes[:10]}")

    fixture = {
        "description": (
            f"Golden HDBSCAN* labels generated by hdbscan "
            f"{hdbscan.__version__ if hasattr(hdbscan, '__version__') else 'unknown'} (Python) "
            f"from the first {N} signals of {source_label}. "
            f"Parameters: min_cluster_size={min_cluster_size}, "
            f"min_samples={min_samples}, metric='cosine' (precomputed), "
            f"cluster_selection_method={CLUSTER_SELECTION_METHOD!r}."
        ),
        "source": source_label,
        "n": N,
        "min_cluster_size": min_cluster_size,
        "min_samples": min_samples,
        "cluster_selection_method": CLUSTER_SELECTION_METHOD,
        "ids": ids,
        "titles": titles,
        "embeddings": embeddings,
        "labels": labels,
    }

    out_path = os.path.join(out_dir, f"golden_{tag}.json")
    with open(out_path, "w") as f:
        json.dump(fixture, f, separators=(",", ":"))
    print(f"  Wrote {out_path}")

print("\nDone.")
